### ISSUE TITLE
Running Metricbeat in kubernetes

### ISSUE THREAD

**Issue by jerroydmoore** [elastic/beats-docker#3]
Running metricbeat in kubernetes, `beats.hostname` is set to the container name, e.g. "metricbeat-v5.2.1-3bhfr".

When running metricbeats in multiple hosts, you will not be able to distinguish one host from another. Furthermore, if metricbeat dies for any reason, it will be assigned a new container name, e.g. "metricbeat-v5.2.1-XXXXX"

**Comment by ruflin** [comment]
Are you looking for a way to configure a name for each instance? For this you can use `beat.name` which is the `name` option in the config. 

What is the actual host name of the container? Is it the same as the container name?

**Comment by jerroydmoore** [comment]
Hey @ruflin 

I remember you vividly from the ElasticON!

Right now, Metricbeat dynamically gets the hostname--no configuration necessary. But when run in containers, when software asks for the hostname, they get the container name instead. This is not very useful for Metricbeat. Imagine running 10 physical hosts, each with a metricbeat container. When viewing reports in Kibana, you will see 10 separate "metricbeat-v5.2.1-XXXXX". Worse yet, if metricbeat needs to restart the "XXXXX" changes values, so you'll end up seeing more than 10 metricbeats!

**Comment by jerroydmoore** [comment]
I've designed a workaround for running metricbeat in kubernetes.

Metricbeat allows you to [embed environment variables into its configuration file](https://www.elastic.co/guide/en/beats/metricbeat/current/using-environ-vars.html). So I've added the following to my metricbeat.yml:
```
name: ${NODE_NAME}
```

To populate the NODE_NAME envvar, you need to add the following 

```
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```
Here is my complete kubernetes daemonset configuration for other people trying to run metricbeats in k8s:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: metricbeat-v5.2.1
  namespace: kube-system
  labels:
    k8s-app: metricbeat
    kubernetes.io/cluster-service: "true"
    version: v5.2.1
spec:
  template:
    metadata:
      labels:
        k8s-app: metricbeat
        kubernetes.io/cluster-service: "true"
        version: v5.2.1
    spec:
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:5.2.1
        command:
          - '/bin/sh'
          - '-c'
          - '/usr/share/metricbeat/metricbeat -e -c /etc/metricbeat/metricbeat.yml -system.hostfs=/hostfs -path.logs /var/log/metricbeat'
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: procpath
          mountPath: /hostfs/proc
          readOnly: true
        #- name: cgroupPath
        #  mountPath: /hostfs/sys/fs/cgroup
        #  readOnly: true
        - name: varlogmetricbeat
          mountPath: /var/log/metricbeat
        - name: metricbeatconf
          mountPath: /etc/metricbeat
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: procpath
        hostPath:
          path: /proc
      #- name: cgroupPath
      #  hostPath:
      #    path: /sys/fs/cgroup
      - name: varlogmetricbeat
        hostPath:
          path: /var/log/metricbeat
      - name: metricbeatconf
        configMap:
          name: metricbeat-conf
```
