### ISSUE TITLE
kibana did not find index 404

### ISSUE THREAD

**Issue by gimler** [elastic/beats-docker#9]
For confirmed bugs, please report:
- Beat Version: 5.3.1
- Operating System: ubuntu
- Docker Version: Docker version 17.04.0-ce, build 4845c56
- Steps to Reproduce: 

The metricbeat is writing data into the elasticsearch i can check that with `http://localhost:9200/_cat/indices?v`

```
health status index                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   .monitoring-kibana-2-2017.04.26 MkrSWQjBRdGEaQf4csUuog   1   1          6            0     63.7kb         63.7kb
yellow open   .kibana                         yEdBQl8JSNqNhVYMMgx77A   5   1         95           67    394.5kb        394.5kb
yellow open   metricbeat-2017.04.26           ZH5tpPqZS52D-P9TQT5mIQ   5   1       2348            0      4.4mb          4.4mb
yellow open   .monitoring-es-2-2017.04.26     SabclaYqQSmKOQ0KUCsKOQ   1   1        194           76    471.1kb        471.1kb
yellow open   .monitoring-data-2              _6MtkjMeQvGNEs0diHJ1Lg   1   1          3            0      6.9kb          6.9kb
```
The index is created and has some fields in kibana.

But "Discover" reports "No results found".

When i try to add the index manually the logs give a 404
```
kibana                       | {"type":"response","@timestamp":"2017-04-26T06:54:58Z","tags":[],"pid":7,"method":"get","statusCode":404,"req":{"url":"/elasticsearch/metricbeat-*/_mapping/field/*?_=1493189698122&ignore_unavailable=false&allow_no_indices=false&include_defaults=true","method":"get","headers":{"host":"localhost:5601","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0","accept":"application/json, text/plain, */*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","kbn-version":"5.3.1","referer":"http://localhost:5601/app/kibana","connection":"keep-alive"},"remoteAddress":"192.168.160.1","userAgent":"192.168.160.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":404,"responseTime":11,"contentLength":9},"message":"GET /elasticsearch/metricbeat-*/_mapping/field/*?_=1493189698122&ignore_unavailable=false&allow_no_indices=false&include_defaults=true 404 11ms - 9.0B"}

```

docker-compose.yml
```
version: '2.1'

services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:5.3.1
    restart: unless-stopped
    networks:
      - beats
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
    command: metricbeat -e -system.hostfs=/hostfs
    environment:
      - http_proxy
      - https_proxy
      - no_proxy=${no_proxy},elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    container_name: elasticsearch
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ports:
      - '127.0.0.1:9200:9200'
    networks:
       - beats
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', 'elastic:changeme', 'http://localhost:9200']

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.1
    container_name: kibana
    ports:
      - '127.0.0.1:5601:5601'
    networks:
       - beats
    depends_on:
      elasticsearch:
        condition: service_healthy

  import_dashboards:
      image: docker.elastic.co/beats/metricbeat:5.3.1
      # Using -beat "" causes it to install all dashboards in the zip and not just the metricbeat ones.
      networks:
        - beats
      command: >-
        /usr/share/metricbeat/scripts/import_dashboards
          -file /usr/share/metricbeat/beats-dashboards-5.3.1.zip
          -es http://elasticsearch:9200
          -user elastic
          -pass changeme
      depends_on:
        elasticsearch:
          condition: service_healthy

  set_default_index_pattern:
      image: docker.elastic.co/beats/metricbeat:5.3.1
      networks:
        - beats
      command: >-
        curl -XPUT http://elastic:changeme@elasticsearch:9200/.kibana/config/5.3.1
          -d '{"defaultIndex" : "metricbeat-*"}'
      depends_on:
        elasticsearch:
          condition: service_healthy

networks:
  beats:
```
